### PR TITLE
Create Simple Python Programs #145.py

### PR DESCRIPTION
**Pull request by uddipbisht**
adding two matrics in Simple Python Programs #145

### CODE REVIEW

**Comment by trishan9** [comment]
Thanks for your contribution!

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Comment by uddipbisht** [comment]
thank u my friend

**Pull request merged**
