### PR TITLE
Readme file updated

### PR DESCRIPTION
**Pull request by Manoj-M-V**
Before : Screenshot 2023-10-03 194128
After : Screenshot 2023-10-03 194515
README.md file has been updated on lines 8, 9 and 12.

### CODE REVIEW

**Review by trishan9 — APPROVED** [review]
LGTM, thanks for your contribution @Manoj-M-V

**Comment by Manoj-M-V** [comment]
Hello sir, can you please add "HACKTOBERFEST-ACCEPTED" label to the MR.

**Comment by trishan9** [comment]
of course

**Comment by trishan9** [comment]
Done, once again thanks for your contribution, @Manoj-M-V !

**Comment by Manoj-M-V** [comment]
Thank you too

**Pull request merged**
