### PR TITLE
hello world in crystal lang

### PR DESCRIPTION
**Pull request by Rudra-choudhary**

### CODE REVIEW

**Review by Rudra-choudhary — COMMENTED** [review]
looks good !

**Review by Rudra-choudhary — COMMENTED** [review]
looks good !

**Comment by trishan9** [comment]
Thanks for your contribution!

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Pull request merged**
