### PR TITLE
Create HelloWorld!.kt

### PR DESCRIPTION
**Pull request by Ishika0-0**
added Hello World in kotlin language

solved issue #194

### CODE REVIEW

**Comment by Ishika0-0** [comment]
@trishan9 I've solved the issue kindly merge it

**Comment by trishan9** [comment]
Thanks for your contribution!

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Comment by Ishika0-0** [comment]
> Thanks for your contribution!

It was great working in your repo!

**Pull request merged**
