### PR TITLE
 Hello world in morse

### PR DESCRIPTION
**Pull request by Ashima-ashi**

### CODE REVIEW

**Comment by trishan9** [comment]
Thanks for your contribution!

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Comment by sandeepM-codes** [comment]
i have one oops project in c++  banking system using oops concepts

**Pull request merged**
