### PR TITLE
Added quick sort in rust

### PR DESCRIPTION
**Pull request by atulsubedi**
A simple rust program for hacktoberfest.

### CODE REVIEW

**Comment by atulsubedi** [comment]
@trishan9 can you take a look at it.

**Comment by trishan9** [comment]
Thanks for your contribution!

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Pull request merged**
