### PR TITLE
Kthsmallestelem

### PR DESCRIPTION
**Pull request by Pooja1030**
Implemented the Kth smallest element in cpp

### CODE REVIEW

**Review by trishan9 — CHANGES_REQUESTED** [review]
please resolve the merge conflicts and update the PR

**Comment by Pooja1030** [comment]
Fixed the issue

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
Thanks for your contribution!

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Pull request merged**
