### PR TITLE
Create Qbasic

### PR DESCRIPTION
**Pull request by YashBajpaiGITHUB**
Sir if you accept it , please add hacktoberfest and accepted label to it.

### CODE REVIEW

**Comment by YashBajpaiGITHUB** [comment]
Most people have done it with the common languages so I thought of QBasic

**Review by trishan9 — APPROVED** [review]
Lgtm

**Comment by trishan9** [comment]
Thanks for your great contribution @YashBajpaiGITHUB

**Comment by YashBajpaiGITHUB** [comment]
Sir it is not updated in the hactoberfest site.

**Comment by YashBajpaiGITHUB** [comment]
@trishan9 Sir please add hacktoberfest, hacktoberfest2023 and hacktoberfest-accepted labels to it. Please sir humble request.

**Pull request merged**
