### PR TITLE
Added quicksort in cpp

### PR DESCRIPTION
**Pull request by Pooja1030**
Implemented the quicksort in the cpp

### CODE REVIEW

**Review by trishan9 — CHANGES_REQUESTED** [review]
please resolve the conflict and update the PR, so that it can be merged!

**Comment by Pooja1030** [comment]
Fixed the issue

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
Thanks for your contribution!

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Pull request merged**
