### PR TITLE
Hello, world with a mojo source file

### PR DESCRIPTION
**Pull request by akashchaudhary-git**
### Description
Added a Hello World program for mojo language.  PR#40 

Please review and consider merging this pull request. Additionally, I kindly request the addition of the Hacktoberfest and Hacktoberfest-Accepted labels to this pull request.

Thank you!
@akashchaudhary-git

### CODE REVIEW

**Review by trishan9 — APPROVED** [review]
Lgtm

**Comment by trishan9** [comment]
Thanks for your great contribution @akashchaudhary-git

**Comment by akashchaudhary-git** [comment]
Hey @trishan9 can you please assign hacktoberfest label.

Thankyou

**Comment by trishan9** [comment]
Done @akashchaudhary-git

**Pull request merged**
