### PR TITLE
Hello world in Html

### PR DESCRIPTION
**Pull request by mohammdowais**
Fixes: #30 #17
Hello world in html with cool animation from Kevin Powel

https://github.com/trishan9/HelloWorld/assets/85205148/2d487414-6b34-4c62-91fe-6411d9cfc93b

### CODE REVIEW

**Comment by mohammdowais** [comment]
@trishan9 do i need to get assigned first to work on an issue? I just made a PR thinking it was in the issue was that okay?

**Comment by trishan9** [comment]
lgtm

**Comment by trishan9** [comment]
Thanks for your contribution @mohammdowais

**Review by trishan9 — APPROVED** [review]
lgtm

**Pull request merged**
