### PR TITLE
Create hello_world.js

### PR DESCRIPTION
**Pull request by Moumita-08**
This is a basic code for beginners in JavaScript.

### CODE REVIEW

**Comment by trishan9** [comment]
Thanks for your contribution!

**Review by trishan9 — APPROVED** [review]
lgtm

**Comment by trishan9** [comment]
PR has been merged under Hacktoberfest!

**Comment by trishan9** [comment]
Happy contribution!

**Comment by Moumita-08** [comment]
> PR has been merged under Hacktoberfest!

Thank You !

**Pull request merged**
