### PR TITLE
Added Hello world in Scratch (scratch.mit.edu)

### PR DESCRIPTION
**Pull request by exilonium**

### CODE REVIEW

**Comment by trishan9** [comment]
Thanks for the contribution!

**Review by trishan9 — APPROVED** [review]
lgtm!

**Comment by trishan9** [comment]
PR has been merged!

**Comment by trishan9** [comment]
Happy contribution!

**Comment by Enigma1309** [comment]
Thank you ❤️

**Comment by exilonium** [comment]
Thank you <3

**Pull request merged**
